name: nodelabs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5

  # iOS ve macOS için Cupertino tarzı ikonlar
  cupertino_icons: ^1.0.8

  # SVG dosyalarını kullanmak için
  flutter_svg: ^2.0.10+1

  # State management için Flutter Bloc (Cubit desteği de var)
  flutter_bloc: ^8.1.5

  # Kullanıcıdan galeri/kamera ile fotoğraf seçmek için
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0

  # HTTP istekleri için Dio paketi
  dio: ^5.4.1

  # Sayfa yönlendirme için Go Router paketi
  go_router: ^13.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/add_icon.svg
    - assets/adduser_icon.svg
    - assets/apple_icon.svg
    - assets/arrowleft_icon.svg
    - assets/facebook_icon.svg
    - assets/fav_icon.svg
    - assets/favnot_icon.svg
    - assets/gem_icon.svg
    - assets/google_icon.svg
    - assets/hide_icon.svg
    - assets/home_icon.svg
    - assets/letter_icon.svg
    - assets/profile_icon.svg
    - assets/unlock_icon.svg
    - assets/default_poster.png
